In [1]:
import torch
from utilities import preprocess_base

device = ("cuda" if torch.cuda.is_available() else "cpu")

data = preprocess_base(
    csv="../data/SIDI_Full.csv",
    target_var="DI",
    split=0.8,
    device=device
)

data[102]

(array([1.  , 1.81, 0.  , 0.  ]), 0.80348)

In [2]:
from utilities import pre_processing_ft

data_ft = pre_processing_ft(data, device)

data_ft[102]

(tensor([0.0000, 0.7838, 0.5100, 0.0000], device='cuda:0', dtype=torch.float64),
 tensor(1.4506, device='cuda:0', dtype=torch.float64))

In [3]:
from utilities import pre_processing_none

data_none = pre_processing_none(data, device)

data_none[102]

(tensor([1.0000, 1.8100, 0.0000, 0.0000], device='cuda:0', dtype=torch.float64),
 tensor(0.8035, device='cuda:0', dtype=torch.float64))

In [5]:
from utilities import pre_processing_f

data_f = pre_processing_f(data, device)

data_f[102]

(tensor([0.0000, 0.7838, 0.5100, 0.0000], device='cuda:0', dtype=torch.float64),
 tensor(0.8035, device='cuda:0', dtype=torch.float64))

In [4]:
from utilities import pre_processing_t

data_t = pre_processing_t(data, device)

data_t[102]

(tensor([1.0000, 1.8100, 0.0000, 0.0000], device='cuda:0', dtype=torch.float64),
 tensor(1.4506, device='cuda:0', dtype=torch.float64))